### ISSUE TITLE
Visual problems in the OUTTRIGGER game (dreamcast version)

### ISSUE THREAD

**Issue by Biryuk666** [twinaphex/reicast-emulator#1113]
Greetings!
I found several visual problems in the OUTTRIGGER game
1) When using full screen mode in the main menu, broken borders are visible
[https://cloud.mail.ru/public/GSUx/zoychV9X4](url)
2) In vs mode, when you need to select a stage, the icon with the selected character is not displayed. And also the borders are displayed incorrectly
[https://cloud.mail.ru/public/Argm/cm9pMUWhP](url)
3) Horizontal borders at the start of the game are not full screen
[https://cloud.mail.ru/public/raZx/RaiyY6A8t](url)
4) Darkness does not work in night missions
[https://cloud.mail.ru/public/ViCC/vSbVw7s3h](url)
5) incorrect display of the player who defeted you. Either only part of the enemy is displayed, or sometimes it is not displayed at all
[https://cloud.mail.ru/public/kht8/1Gx63YBq5](url)
6) The inscription "get it" is not displayed above the medals
[https://cloud.mail.ru/public/g3zH/v2NTtwVvW](url)

**Comment by flyinghead** [comment]
The border issues are due to enabling Widescreen. This option will display geometry outside the 4:3 format that would not be normally visible. So graphical glitches and artifacts are to be expected in this area. Disabling Widescreen will fix it. (Items 1, 2 & 3)

Item 2: I confirm the problem.

Item 4; Darkness does work for my version of the game. The screenshot isn't what is displayed when starting the Dark Busy Station area. If you're using a CDI, it's possible that the image was replaced to save space.

Item 5: I can't reproduce this. The player who defeats me appears in a window for a couple of seconds, then the flashing body of the player. 

Item 6: I can't reproduce it either. There's a Get It sprite above the medals.

Please check your game media and prefer CHD or GDI.

Also, what GPU are you using and which renderer (open gl, vulkan)? What are your settings?

**Comment by Biryuk666** [comment]
Hello! I am playing on the GDI image of the NTSC-USA game. 

My settings for the game here: 
[https://cloud.mail.ru/public/pJD8/nnvWdnjQg](url)
and a video about how the game should be displayed in dark locations, with screen of your destroyer and the inscription "get it" above the medals here:
[https://cloud.mail.ru/public/NHFj/4n4wbmzBH](url)
Location on video - dark castle

My graphics card is a Radeon rx 480 8gb. Play on retroarch steam version

**Comment by flyinghead** [comment]
![RetroArch Flycast v1 1-54-gc6fe6b8 __ FPS_  58 96 12_15_2021 5_04_00 PM](https://user-images.githubusercontent.com/16261910/146223440-1a4e6287-d8ff-4f0c-8303-fafde7d8de75.png)
![RetroArch Flycast v1 1-54-gc6fe6b8 __ FPS_  60 06 12_15_2021 5_10_43 PM](https://user-images.githubusercontent.com/16261910/146223497-157ceca0-e911-415b-b8b3-07dbc7d584a0.png)
![RetroArch Flycast v1 1-54-gc6fe6b8 __ FPS_  60 06 12_15_2021 5_13_15 PM](https://user-images.githubusercontent.com/16261910/146223522-b67d2f10-cc38-4e3b-9bb9-18973c3b8565.png)

Core version: 1.1-54-gc6fe6b8

Your settings are crazy. Texture upscaling x6? Force Windows CE? Please delete your flycast settings to reset them to default and only change the settings you need. Do NOT use texture upscaling.

**Comment by Biryuk666** [comment]
Can you send me your settings? I deleted the settings as you said, but "your destroyer's" screen still doesn't show normally
[https://cloud.mail.ru/public/cgkm/9Hj4iMrkk](url)
[https://cloud.mail.ru/public/gJcH/WW4P7JYvv](url)

P.S. Thank you very much! You are breathetaking!

**Comment by Biryuk666** [comment]
I made the decision to put up with it. Thank you for your help! I only ask you to fix the bug with the character icon when choosing a level
